### call root
GET http://localhost:8080/

### call retornaJSON
POST http://localhost:8080/retornaJSON
Content-Type: application/json

{
    "inputValue": "{\"attr1\": \"value1\", \"attr2\": \"value2\"}"
}     


### call approverRetrieve
POST http://localhost:8080/approverRetrieve
Content-Type: application/json

{
    "inputValue": "{\"result\": {\"responseArray\": [{\"id\": \"647\",\"type\": \"USERTASK_COMPLETED\",\"taskId\": \"2cfbf297-736e-11ee-b330-eeee0a898568\",\"userId\": \"renato.bonini@numenit.com\",\"subject\": \"Aprovar Pedido\",\"timestamp\": \"2023-10-25T19:40:21+00:00\",\"activityId\": \"form_formAprovPedido_3\",\"referenceInstanceId\": \"bcc6cd2e-72d4-41b4-a1bd-01546119f4b7\"},{\"id\": \"648\",\"type\": \"ACTIONTASK_CREATED\",\"subject\": \"Retrieve process execution logs\",\"timestamp\": \"2023-10-25T19:40:21+00:00\",\"activityId\": \"action_get_getV1WorkflowInstancesWorkflowInstanceIdExecutionLogs_1\",\"referenceInstanceId\": \"557e476c-736e-11ee-8a32-eeee0a958625\"}]}}"
}     
  
### call approverRetrieve Cloud Foundry
POST https://cf22-srv.cfapps.us10-001.hana.ondemand.com/approverRetrieve
Content-Type: application/json

{
    "inputValue": "{\"result\": {\"responseArray\": [{\"id\": \"647\",\"type\": \"USERTASK_COMPLETED\",\"taskId\": \"2cfbf297-736e-11ee-b330-eeee0a898568\",\"userId\": \"renato.bonini@numenit.com\",\"subject\": \"Aprovar Pedido\",\"timestamp\": \"2023-10-25T19:40:21+00:00\",\"activityId\": \"form_formAprovPedido_3\",\"referenceInstanceId\": \"bcc6cd2e-72d4-41b4-a1bd-01546119f4b7\"},{\"id\": \"648\",\"type\": \"ACTIONTASK_CREATED\",\"subject\": \"Retrieve process execution logs\",\"timestamp\": \"2023-10-25T19:40:21+00:00\",\"activityId\": \"action_get_getV1WorkflowInstancesWorkflowInstanceIdExecutionLogs_1\",\"referenceInstanceId\": \"557e476c-736e-11ee-8a32-eeee0a958625\"}]}}"
}    

//{"result": {"responseArray": [{"id": "647","type": "USERTASK_COMPLETED","taskId": "2cfbf297-736e-11ee-b330-eeee0a898568","userId": "renato.bonini@numenit.com","subject": "Aprovar Pedido","timestamp": "2023-10-25T19:40:21+00:00","activityId": "form_formAprovPedido_3","referenceInstanceId": "bcc6cd2e-72d4-41b4-a1bd-01546119f4b7"},{"id": "648","type": "ACTIONTASK_CREATED","subject": "Retrieve process execution logs","timestamp": "2023-10-25T19:40:21+00:00","activityId": "action_get_getV1WorkflowInstancesWorkflowInstanceIdExecutionLogs_1","referenceInstanceId": "557e476c-736e-11ee-8a32-eeee0a958625"}]}}